# Generated by Django 3.2 on 2022-04-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogisland', '0002_auto_20220429_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
