# Generated by Django 3.2 on 2022-04-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogisland', '0003_remove_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
