# Generated by Django 3.2 on 2022-04-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogisland', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(
                default=1,
                max_length=60,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='category',
                to='blogisland.category'),
        ),
    ]
